; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-stamps3]
platform = espressif32
board = m5stack-stamps3
framework = arduino
lib_deps = m5stack/M5Unified@^0.2.11

upload_port = /dev/cu.usbmodem2101
monitor_port = /dev/cu.usbmodem2101

; set buad rate for the serial monitor
monitor_speed = 115200
; monitor_dtr = 1
; monitor_rts = 1

; build flags

; description based on Gemini results.
;   ARDUINO_USB_CDC_ON_BOOT routes UART over USB(CDC) rather then a sperate UART pin on hardware.
;       CDC: "Communication Device Class"
;           emulates tradional USB devices.

;   ARDUINO_USB_MODE=1        enables Hardware (CDC/JTAG) MODE (the hardware cdc has keyboard)
;   ARDUINO_USB_MODE=0      uses the TinyUSB Software Stack. 
;       This is a software lib that can emulate and USB class like HID, mass storage, but also CDC (which will still allow us to use Serial over USB)


build_unflags = 
    -D ARDUINO_USB_MODE=1
build_flags = 
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MSC_ON_BOOT=1
