[env:esp32-s3-wroom-1-n8r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

upload_port = /dev/cu.usbmodem101

; --- Memory & Hardware Configurations for N8R8 ---
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608

build_flags = 
    ; Enable PSRAM support in the ESP-IDF/Arduino framework
    -D BOARD_HAS_PSRAM
    
    
    ; Configure the PSRAM for Octal SPI (required for the 8MB R8 chip)
    -D CONFIG_SPIRAM_MODE_OCT=1
    
    ; Direct Serial output to native USB CDC if you're bypasssing a CP210x chip
    -D ARDUINO_USB_MODE=0 # 0 = TinyUSB (software CDC), 1 = Hardware CDC (native USB no serial) 
    -D ARDUINO_USB_CDC_ON_BOOT=1